### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by HitomiFlower** [HitomiFlower/NaoMahjong#1]
# Version 1.2

###  fix

 - [x] Warning info will overflow the panel
 - [x] The "Room" scene character image missing.
 - [x] The "Room" scene layout will be not display corrected in some resolution.
 - [x] Player and room name display incorrectly when Chinese name has number or English

### fix

 - [x] Fix the DOTween exception in the "Play" scene.
 - [x] Room transition effect will play event the room doesn't existed.
 - [x] Room agent quit to the lobby can still see the room with 0/0 player.

### improvemnt

- [x] Make the transition more influence.
- [x] Add SE
- [x] Add BGM

# Version 1.3

### fix

 - [ ] Advanced rule setting windows will be opened when closed in that status
 - [ ] Player can still discard tile even in other player turn. (A display bug)

### feature

- [ ] Add simple AI
- [ ] Add "character select" 

# Version 1.4

### Gameplay feature

- [ ] Load audio file from local disk
- [ ] Load audio file from network
- [ ] Sync the audio from network

# Version 1.5

### UI improvement

 - [ ] Replace the text component to TestMeshPro text

# Version 2.0

### UI improvement

 - [ ] Replace the UI texture with original texture

# Version 2.1

### Gameplay improvemnt

- [ ] Add advanced AI
